<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ECHECK_CHECKING</name>
   <tag></tag>
   <elementGuidId>c1a5fa8a-c70e-4b96-8c90-d8fb0ecff6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ctl00_mainContent_achAccountTypeRow&quot;]/div[2]/fieldset/span[1]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
